# Site settings
title:       SPi 双拼输入法 for iPhone
email:       spi-support@guoc.name
author:      guoc
description: "在iPhone上简单地打双拼"
baseurl:     ""
url:         "http://spi.guoc.name"

# Google analytics
google_analytics: "UA-57747253-2"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
