# Site settings
title:       SPi 双拼输入法 for iPhone
email:       support@spiim.com
author:      guoc
description: "在iPhone上简单地打双拼"
baseurl:     ""
url:         "http://spiim.com"

# Google analytics
google_analytics: "UA-57747253-2"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    /blog/:title.html
paginate:     3
paginate_path: "blog/page:num/"
sass:
  compressed: true
